### ISSUE TITLE
Enriquecer documentación liquid

### ISSUE THREAD

**Issue by ghost** [gmontero/bsale-market-design-doc#1]
Hay que agregar la validación de strings vacíos.

**Comment by ghost** [comment]
Agregar documentacion para {% raw %}

**Comment by iquinones-bsale** [comment]
hola, hemos agregado `{% raw %}` a la documentación [aquí](https://github.com/gmontero/bsale-market-design-doc/wiki/Utilizar-framework-JS-en-Liquid-%28Mustache%2C-Handlebars%2C-Vue-etc...%29)
