### ISSUE TITLE
Template 8 Habilitar nuevo Slide

### ISSUE THREAD

**Issue by huenre9** [gmontero/bsale-market-design-doc#2]
Habilite le nuevo slide en un cliente con template 8, la configuración del carrusel no funciona, solo toma algunos parámetros en la configuración, que son "Cambiar con deslizar en pantalla tactil" "Elementos visibles" "flechas de navegación"

Los demás no funcionaron, ademas de eso cuando se habilitan las flechas, aparecen los DOTS y las flechas sin diseño.

En celular, el menu se posiciona mas abajo del slide.

**Comment by huenre9** [comment]
Al intentar reparar con https://github.com/gmontero/bsale-market-design-doc/wiki/Reparaci%C3%B3n-Slider-Carrusel 
No muestra las imagenes, la clase display quede en estado: none

**Comment by iquinones-bsale** [comment]
Hola, se me había olvidado responderte por acá, eso ya quedo solucionado https://newtemplate8-b.bsalemarket.com
